import type { Metadata } from 'next'
import { Vazirmatn } from 'next/font/google'
import { ClerkProvider } from '@clerk/nextjs'

import './globals.css'
import ToastProvider from '@/components/provider/toast-proviser'
import { ConfettiProvider } from '@/components/provider/confettiProvider'

const vazir = Vazirmatn({ 
  subsets: ['arabic'],
  weight: "600",
  variable: "--font-vazir"
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <html lang="fa" dir='rtl'>
        <body className={`${vazir.variable} font-vazir`}>
          <ConfettiProvider />
          <ToastProvider />
          {children}
        </body>
      </html>
    </ClerkProvider>
  )
}
